name: test
on: [push, pull_request]

jobs:
  opam:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ocaml:
        - 5.0.x
        - 4.14.x
        - 4.13.1
        - 4.12.1
        - 4.11.2
        - 4.10.2
        - 4.09.1
        - 4.08.1
        - 4.07.1
        - 4.06.1
        - 4.05.0
        - 4.04.2
        - 4.03.0

    steps:
    - uses: actions/checkout@v2
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{matrix.ocaml}}
    - run: opam install --deps-only --with-test . --yes
    - run: opam exec -- make test
    - run: opam lint
    - if: ${{matrix.ocaml == '4.13.1'}}
      env:
        COVERALLS_REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PULL_REQUEST_NUMBER: ${{github.event.number}}
      run: |
        opam exec -- make clean coverage
        opam exec -- bisect-ppx-report send-to Coveralls
