name: test
on: [push, pull_request]

jobs:
  opam:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ocaml:
        - 5
        - 4
        - 4.03.0

    steps:
    - uses: actions/checkout@v4
    - uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: ${{matrix.ocaml}}
    - run: opam install --deps-only --with-test . --yes
    - run: opam exec -- make test
    - run: opam lint
    - if: ${{matrix.ocaml == '5'}}
      env:
        COVERALLS_REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PULL_REQUEST_NUMBER: ${{github.event.number}}
      run: |
        opam exec -- make clean coverage
        opam exec -- bisect-ppx-report send-to Coveralls
